<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup><TargetFramework>netstandard2.0</TargetFramework></PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\QS3D.Platform.Cad.Abstractions\QS3D.Platform.Cad.Abstractions.csproj" />
    <ProjectReference Include="..\QS3D.Platform.Domain\QS3D.Platform.Domain.csproj" />
  </ItemGroup>
</Project>
