<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup><TargetFramework>net8.0</TargetFramework></PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\QS3D.Platform.Domain\QS3D.Platform.Domain.csproj" />
    <ProjectReference Include="..\QS3D.Platform.Geometry\QS3D.Platform.Geometry.csproj" />
  </ItemGroup>
</Project>
